# Generated by Django 4.0 on 2022-01-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stucon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default_pic.png', upload_to='images/'),
        ),
    ]
