# Generated by Django 4.0 on 2022-02-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stucon', '0002_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='default_pic.png', null=True, upload_to='images/'),
        ),
    ]
