# Generated by Django 4.0 on 2022-02-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stucon', '0003_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default_pic.png', upload_to='images/'),
        ),
    ]
