# Generated by Django 4.0 on 2022-01-24 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(default='', max_length=300)),
                ('type', models.CharField(choices=[('subj', 'Subjective'), ('time', 'Timed'), ('count', 'Count'), ('pf', 'Pass Fail')], default='subj', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveEvolution',
            fields=[
                ('evolution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rubric.evolution')),
                ('good_score', models.PositiveIntegerField(blank=True, null=True)),
                ('bad_score', models.PositiveIntegerField(blank=True, null=True)),
            ],
            bases=('rubric.evolution',),
        ),
        migrations.AddField(
            model_name='evolution',
            name='traits',
            field=models.ManyToManyField(to='rubric.Trait'),
        ),
    ]
