# Generated by Django 4.0 on 2022-01-24 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rubric', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TraitScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(choices=[(1, '0'), (2, '1'), (3, '2'), (4, '3'), (5, '4')])),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('evolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubric.evolution')),
                ('grader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_grader', to='auth.user')),
            ],
        ),
    ]
